// Originally generated by ts-to-zod
import { z } from "zod";
import {
  ICalEventRepeatingFreq,
  ICalWeekday,
} from "./../vendor/IcalGeneratorTypes";

// Modified to actually expect dttm
export const iCalDateTimeValueSchema = z.coerce.date(); //.string().datetime();

export const iCalEventRepeatingFreqSchema = z.nativeEnum(
  ICalEventRepeatingFreq
);

export const iCalWeekdaySchema = z.nativeEnum(ICalWeekday);

export const iCalGeoSchema = z.object({
  lat: z.number(),
  lon: z.number(),
});

export const iCalRepeatingOptionsSchema = z.object({
  freq: iCalEventRepeatingFreqSchema,
  count: z.number().optional(),
  interval: z.number().optional(),
  until: iCalDateTimeValueSchema.optional(),
  byDay: z.union([z.array(iCalWeekdaySchema), iCalWeekdaySchema]).optional(),
  byMonth: z.union([z.array(z.number()), z.number()]).optional(),
  byMonthDay: z.union([z.array(z.number()), z.number()]).optional(),
  bySetPos: z.union([z.array(z.number()), z.number()]).optional(),
  exclude: z
    .union([z.array(iCalDateTimeValueSchema), iCalDateTimeValueSchema])
    .optional(),
  startOfWeek: iCalWeekdaySchema.optional(),
});

export const iCalLocationSchema = z.object({
  title: z.string(),
  address: z.string().optional(),
  radius: z.number().optional(),
  geo: iCalGeoSchema.optional(),
});
